project_name: ice
release:
  github:
    owner: NimbleArchitect
    name: kubectl-ice
builds:
  - id: ice
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/NimbleArchitect/kubectl-ice/pkg/version.version=
archives:
  - id: ice
    builds:
    - ice
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
