apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ice
spec:
  version: {{ .TagName }}
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha https://github.com/NimbleArchitect/kubectl-ice/releases/download/{{ .TagName }}/ice_{{ .TagName }}_linux_amd64.tar.gz .TagName }}
    files:
    - from: "./ice"
      to: "."
    - from: LICENSE
      to: "."
    bin: "ice"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha https://github.com/NimbleArchitect/kubectl-ice/releases/download/{{ .TagName }}/ice_{{ .TagName }}_darwin_amd64.tar.gz .TagName }}
    files:
    - from: "./ice"
      to: "."
    - from: LICENSE
      to: "."
    bin: "ice"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha https://github.com/NimbleArchitect/kubectl-ice/releases/download/{{ .TagName }}/ice_{{ .TagName }}_windows_amd64.zip .TagName }}
    files:
    - from: "/ice.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "ice.exe"
  shortDescription: A new plugin
  homepage: https://github.com/NimbleArchitect/kubectl-ice
  caveats: |
    Usage:
      $ kubectl ice

    For additional options:
      $ kubectl ice --help
      or https://github.com/NimbleArchitect/kubectl-ice/blob/{{ .TagName }}/README.md

  description: |
    Plugin to view info on the containers within a pod
