apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ice
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/NimbleArchitect/kubectl-ice/releases/download/v0.1.0/ice_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./ice"
      to: "."
    - from: LICENSE
      to: "."
    bin: "ice"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/NimbleArchitect/kubectl-ice/releases/download/v0.1.0/ice_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./ice"
      to: "."
    - from: LICENSE
      to: "."
    bin: "ice"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/NimbleArchitect/kubectl-ice/releases/download/v0.1.0/ice_windows_amd64.zip
    sha256: ""
    files:
    - from: "/ice.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "ice.exe"
  shortDescription: A new plugin
  homepage: https://github.com/NimbleArchitect/kubectl-ice
  caveats: |
    Usage:
      $ kubectl ice

    For additional options:
      $ kubectl ice --help
      or https://github.com/NimbleArchitect/kubectl-ice/blob/v0.1.0/doc/USAGE.md

  description: |
    ice lets you view configuration settings of containers inside pods.
