apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/NimbleArchitect/kubectl-pod/releases/download/v0.1.0/pod_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./pod"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/NimbleArchitect/kubectl-pod/releases/download/v0.1.0/pod_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./pod"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/NimbleArchitect/kubectl-pod/releases/download/v0.1.0/pod_windows_amd64.zip
    sha256: ""
    files:
    - from: "/pod.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod.exe"
  shortDescription: A new plugin
  homepage: https://github.com/NimbleArchitect/kubectl-pod
  caveats: |
    Usage:
      $ kubectl pod

    For additional options:
      $ kubectl pod --help
      or https://github.com/NimbleArchitect/kubectl-pod/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
